# Generated by Django 2.2.7 on 2021-04-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorityApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='send_email_with_image',
            name='status',
            field=models.CharField(default='Unsolved', max_length=10),
        ),
    ]
