# Generated by Django 2.2.7 on 2021-03-31 10:41

from django.db import migrations, models
import django.db.models.deletion
import farmerApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us_tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=50)),
                ('farmer_email', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='farmer_registration_tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=farmerApp.models.path_and_rename)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('mobile_no', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('account_status', models.CharField(default='active', max_length=10)),
                ('timestamp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='questions_tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=400)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=farmerApp.models.ask_query_path_and_rename1)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=farmerApp.models.ask_query_path_and_rename2)),
                ('tags', models.CharField(max_length=50)),
                ('timestamp', models.CharField(max_length=20)),
                ('status', models.CharField(default='not answered', max_length=15)),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerApp.farmer_registration_tbl')),
            ],
        ),
        migrations.CreateModel(
            name='history_of_searched_questions_tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerApp.farmer_registration_tbl')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerApp.questions_tbl')),
            ],
        ),
        migrations.CreateModel(
            name='comments_tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=400)),
                ('timestamp', models.CharField(max_length=20)),
                ('likes', models.PositiveSmallIntegerField(default=0)),
                ('dislikes', models.PositiveSmallIntegerField(default=0)),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerApp.farmer_registration_tbl')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerApp.questions_tbl')),
            ],
        ),
    ]
