# Generated by Django 2.2.7 on 2021-04-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us_tbl',
            name='status',
            field=models.CharField(default='Unsolved', max_length=10),
        ),
    ]
