# Generated by Django 2.2.7 on 2021-03-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=15)),
                ('source', models.CharField(max_length=50)),
                ('thumbnail', models.CharField(max_length=15000)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
