# Generated by Django 2.2.7 on 2021-04-05 05:36

from django.db import migrations, models
import feedsApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='uploading_date',
            field=models.CharField(default=feedsApp.models.check, max_length=20),
        ),
    ]
